# Exp 2

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sb

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
from sklearn import metrics

In [8]:
from sklearn.metrics import classification_report,confusion_matrix

In [9]:
from sklearn.metrics import accuracy_score

In [10]:
from sklearn.datasets import load_iris

In [11]:
from sklearn.datasets import load_iris

In [16]:
iris=load_iris()

In [17]:

print(iris.DESCR)


.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [18]:
df_iris=pd.DataFrame(iris.data,columns=iris.feature_names)
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [19]:
df_iris.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [21]:
df_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [22]:
df_iris.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [23]:
display(df_iris)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [24]:

df_iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df_iris['Class'] = iris.target

df_iris


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Class  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [25]:
def map_species(target):
    species_map = {0: 'Setosa', 1: 'Versicolor', 2: 'Virginica'}
    return species_map[target]

In [26]:
df_iris['Species'] = df_iris['Class'].apply(map_species)

In [27]:
df_iris.drop('Class', axis=1, inplace=True)

In [28]:

num_records, num_features = df_iris.shape
print(f"Number of records: {num_records}")
print(f"Number of features: {num_features}")


Number of records: 150
Number of features: 5


In [29]:
records_per_class = df_iris['Species'].value_counts()
print("Number of records per class:")
print(records_per_class)


Number of records per class:
Setosa        50
Versicolor    50
Virginica     50
Name: Species, dtype: int64


In [30]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Species            150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [31]:
print("\nNumerical description of the DataFrame:")
print(df_iris.describe())


Numerical description of the DataFrame:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000  


In [32]:
missing_values = df_iris.isnull().sum()
print("Missing values in the DataFrame:")
print(missing_values)

Missing values in the DataFrame:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Species              0
dtype: int64


In [33]:
X = df_iris.drop('Species', axis=1)
y = df_iris['Species']

In [34]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25, stratify=y, random_state=42)

In [35]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [36]:
knn_model.fit(train_X, train_y)

KNeighborsClassifier()

In [37]:
predictions = knn_model.predict(test_X)

In [38]:
accuracy = accuracy_score(test_y, predictions)
print("Model Accuracy:", accuracy)

Model Accuracy: 0.9736842105263158


In [39]:
predictions = knn_model.predict(test_X)

In [40]:
comparison_df = pd.DataFrame({'Actual Output': test_y, 'Predicted Output': predictions})
comparison_df

Actual Output Predicted Output
42         Setosa           Setosa
56     Versicolor       Versicolor
99     Versicolor       Versicolor
53     Versicolor       Versicolor
38         Setosa           Setosa
85     Versicolor       Versicolor
134     Virginica        Virginica
141     Virginica        Virginica
107     Virginica        Virginica
132     Virginica        Virginica
106     Virginica       Versicolor
140     Virginica        Virginica
69     Versicolor       Versicolor
84     Versicolor       Versicolor
18         Setosa           Setosa
10         Setosa           Setosa
20         Setosa           Setosa
63     Versicolor       Versicolor
14         Setosa           Setosa
96     Versicolor       Versicolor
147     Virginica        Virginica
93     Versicolor       Versicolor
138     Virginica        Virginica
51     Versicolor       Versicolor
116     Virginica        Virginica
57     Versicolor       Versicolor
41         Setosa           Setosa
127     Virginica        Virginica
7          Setosa           Setosa
77     Versicolor       Versicolor
108     Virginica        Virginica
104     Virginica        Virginica
22         Setosa           Setosa
28         Setosa           Setosa
35         Setosa           Setosa
23         Setosa           Setosa
148     Virginica        Virginica
66     Versicolor       Versicolor

In [41]:
predictions = knn_model.predict(test_X)

In [42]:
print("Classification Report:")
print(classification_report(test_y, predictions))

Classification Report:
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        12
  Versicolor       0.93      1.00      0.96        13
   Virginica       1.00      0.92      0.96        13

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [43]:
print("Confusion Matrix:")
print(confusion_matrix(test_y, predictions))


Confusion Matrix:
[[12  0  0]
 [ 0 13  0]
 [ 0  1 12]]


In [44]:
new_record = pd.DataFrame([[5.1, 3.5, 1.4, 0.2]], columns=X.columns)

In [45]:
predicted_class = knn_model.predict(new_record)
print("Predicted Class Label:", predicted_class[0])


Predicted Class Label: Setosa
